version: "3.8"
services:
  be:
    build: ./be
    container_name: sms-app-be
    ports:
      - "8000:8000"
  fe:
    build: ./fe
    container_name: sms-app-fe
    ports:
      - "4200:4200"
    links:
      - be

